---
- name: Prometheus Operator Start
  hosts: localhost 
  gather_facts: false
  tasks:
  - name: Set Prometheus Operator install 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_prometheus_operator:
          title: "Prometheus Operator Install"
          playbook: "playbooks/openshift-prometheus-operator/config.yml"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: Prometheus Operator
  hosts: localhost
  vars:
     playbook_debug: true
  tasks:
  - import_role:
      name: openshift_prometheus_operator

- name: Prometheus Operator Install Checkpoint End
  hosts: localhost 
  gather_facts: false
  tasks:
  - name: Set Prometheus Operator install 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_prometheus_operator:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
